name: Daily
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 16 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: actions/github-script@v6
        id: svg
        with:
          result-encoding: string
          script: |
            const script = require('./scripts/screenshot.js')
            return await script({github, context, core})
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          path: README.md
          content: |
            <img src="${{ steps.svg.outputs.result }}"/>
          commit_message: 'chore: embed calendar [skip ci]'
          opening_comment: '<!-- [START DAILY SAYING] -->'
          closing_comment: '<!-- [END DAILY SAYING] -->'
